# Generated by Django 2.0.4 on 2018-04-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proj_hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=35)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('cost_center', models.CharField(max_length=10)),
                ('prod_grp', models.CharField(max_length=10)),
                ('hours', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
