# Generated by Django 2.0.4 on 2018-04-13 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proj_hours',
            name='project',
            field=models.CharField(default=3378, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proj_hours',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
