# Generated by Django 2.0.4 on 2018-04-13 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180413_1118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proj_hours',
            new_name='Project_log',
        ),
    ]
